from pytgcalls import exceptions

print("--- Names available in pytgcalls.exceptions ---")
print(dir(exceptions))
print("---------------------------------------------")
print("\nPlease copy the list of names and send it back to me.")